### ISSUE TITLE
In /login page TokenMismatchException

### ISSUE THREAD

**Issue by croxarens** [kalenjordan/commercehero-issues#71]
I was in the /login page and I guess my browser stored the cookie for a while.. so when I clicked on "login" I got this exception.

It comes from the file VerifyCsrfToken.php line 68.

The error page was showing all the tracking of the calls with the library names.

I'm opening this ticket because I think it can be managed in a different way instead of showing the debugging page.

**Comment by kalenjordan** [comment]
Thanks! I had the debug mode on temporarily - should be off now.
